In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("powerplant_data.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB

In [7]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [9]:
# Convert the data into X and y datasets

X = df.drop("PE", axis = 1)
y = df['PE']

In [11]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [13]:
# Split the data into train and test datasets 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [14]:
X_train.head()

         AT      V       AP     RH
5487  25.24  63.47  1011.30  66.21
3522  26.09  70.40  1007.41  85.37
6916  26.63  73.68  1015.15  85.13
7544  32.06  71.85  1007.90  56.44
7600  28.70  71.64  1007.11  69.85

In [17]:
# Scale the data using the StandardScaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
X_train_scaled

array([[ 0.74805289,  0.72006931, -0.32660017, -0.49711722],
       [ 0.86181948,  1.26515721, -0.98521113,  0.8181501 ],
       [ 0.93409473,  1.52314975,  0.32523844,  0.80167494],
       ...,
       [-0.22097078, -0.834965  ,  0.36756563, -0.83554456],
       [ 0.94747903,  1.14245344, -0.41971997, -0.45455637],
       [-1.77355014, -1.19049131,  1.92520594,  0.91837402]])

In [56]:
# We Use the all model to get the more accuracy score

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

models = [
    ("Linear Regression", LinearRegression()),
    ("KNN", KNeighborsRegressor(n_neighbors=2)),
    ("SVR", SVR(C=1.0, epsilon=0.2)),
    ("Decision Tree", DecisionTreeRegressor(random_state=42)),
    ("Gradient Boosting", GradientBoostingRegressor(random_state=42)),
    ("Random Forest", RandomForestRegressor(max_depth=2, random_state=42))
]

results = []

for name, model in models :
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    # print(f" {name} with R2 Score : ", r2_score(y_test, y_pred))
    results.append({
        "Model": name,
        "R2 Score": r2_score(y_test, y_pred),
        "MAE": mean_absolute_error(y_test, y_pred),
        "RMSE": np.sqrt(mean_squared_error(y_test, y_pred))
    })

data = pd.DataFrame(results)

print(data)

 Linear Regression with R2 Score :  0.9314747936670361
 KNN with R2 Score :  0.9484261734155816
 SVR with R2 Score :  0.9432934388320825
 Decision Tree with R2 Score :  0.9305797706367657
 Gradient Boosting with R2 Score :  0.9514453856425776
 Random Forest with R2 Score :  0.8884569918580271
               Model  R2 Score       MAE      RMSE
0  Linear Regression  0.931475  3.543448  4.428102
1                KNN  0.948426  2.666844  3.841555
2                SVR  0.943293  3.096974  4.028182
3      Decision Tree  0.930580  3.028098  4.456926
4  Gradient Boosting  0.951445  2.869884  3.727414
5      Random Forest  0.888457  4.416015  5.649547

In [60]:
# model = LinearRegression()
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
print(r2_score(y_test, y_pred))

0.9314747936670361